Feature/carplay livestream programs
SRGSSR/playsrg-apple pull request #217
Opened 2022-08-16 09:55 UTC by pyby

### Motivation and Context

We got a user feedback asking programs in the livestreams feature.
See #216.

### Description

When to display programs from the livestreams with DVR? In a new view.
When ? Only if the livestream has program. User can select to play the livestream or a previous program.

Start over and skip to live options in the player are helpful to navigate in programs or going back to live.

### Checklist

- [ ] The branch has been rebased onto the `develop` branch.
- The code followed the code style:
	-  [ ] `swiftlint` has run to ensure the *Swift* code style is valid.
	-  [ ] `rubocop -a` has run to ensure the *Ruby* code style is valid.
- [ ] Remote configuration properties have been properly documented (if relevant).
- [ ] The documentation has been updated (if relevant).
- [ ] Issues are linked to the PR, if any.

2022-09-07 14:24 UTC, defagos requested changes
- The file `start_over-2.afdesign` is not a resource and should be deleted.

2022-09-07 14:29 UTC, defagos commented on Application/Sources/CarPlay/CarPlayList.swift
> +            .mapToSection(with: interfaceController)
Maybe `mapToSections(with:)` could be kept as a simple method calling `mapToSection(with:)` and mapping the output to an array.

2022-09-07 14:36 UTC, defagos commented on Application/Sources/CarPlay/CarPlayNowPlayingController.swift
> +                    .prepend(Self.nowPlayingButtons(for: SRGLetterboxService.shared.controller, interfaceController: interfaceController))
Shouldn't `controller` be used instead of `SRGLetterboxService.shared.controller`?

2022-09-07 16:10 UTC, defagos commented on Application/Sources/CarPlay/CarPlayNowPlayingController.swift
> +                template.isUpNextButtonEnabled = Self.isUpNextButtonEnabled
The `isUpNextButtonEnabled` could likely be delivered by a single pipeline delivering now playing buttons and a boolean flag, so that service controller updates are treated consistently.

2022-09-08 15:46 UTC, pyby commented on Application/Sources/CarPlay/CarPlayNowPlayingController.swift
> +                    .prepend(Self.nowPlayingButtons(for: SRGLetterboxService.shared.controller, interfaceController: interfaceController))
Nice findings. Thanks. That's correct.

2022-09-08 16:57 UTC, pyby commented
I dismissed one review because after pushed the commit to remove the file, I wasn't able to answer to the comment and close de conversation. Sorry.

2022-09-08 16:59 UTC, merged