PLAYRTS-5578 - iOS 18 Update
SRGSSR/playsrg-apple pull request #512
Opened 2024-08-15 15:19 UTC by bilqisium

## Description

1. A crash was occurring when building against the iOS 18 SDK. On regular horizontal size class, the UITabBar adopts now a new design paradigm. An internal change caused the UITabBar to not live in the same view hierarchy anymore. This caused a crash within the AutoLayout engine because the two views we were trying to constrain together didn't have a common ancestor.
2. The new UITabBar design paradigm caused issues with the Mini Player and the GoogleCast button positions on regular horizontal size class.

This PR solves both issues.

## Changes Made

Both issues were fixed by:
- Aligning the Mini Player to the safe area on regular horizontal size class, since the UITabBar is not there anymore anyway. On compact size class, we have to rely on computing the UITabBar's height in order to achieve the same result as the current version.
- The GoogleCast button was misplaced on regular horizontal size class as well, since the new floating UITabBar moves the safe area. It's now fixed manually, which isn't ideal so I'm open to better ways to do it.
 

## Checklist

- [x] I have followed the project's style guidelines.
- [x] I have performed a self-review of my own changes.
- [x] I have made corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have tested my changes and I am confident that it works as expected and doesn't introduce any known regressions.
- [x] I have reviewed the contribution guidelines.

2024-08-15 20:33 UTC, defagos reviewed
I tested the result in the simulator on iOS 18 and on an iOS 17 device. Two quick feedbacks without diving too much into the code yet:

- Restoring the small vertical space between the player bar and the bottom bar would be nicer IMHO.
- The TV program header seems broken, on iPad at least. Maybe a simulator thing, this needs to be tested on a device running the latest beta.

2024-08-15 20:41 UTC, defagos commented
A suggestion also: You might want to assign the `.search` [role](https://www.donnywals.com/using-ios-18s-new-tabview-with-a-sidebar/) to the corresponding tab item so that it is displayed in the standard position on the right.

2024-08-16 06:44 UTC, defagos commented
The settings button is also not visible anymore in the _Profile_ section on iPadOS 18.

2024-08-16 11:19 UTC, pyby requested changes

2024-08-16 11:19 UTC, pyby commented on Application/Sources/Content/PageViewController.swift
> +                    if traitCollection.horizontalSizeClass == .regular {
Should we keep the same previous offset for iPadOS previous 18 and introduce an os version check?
The new condition should be only for iPadOS 18 and more. 

UI change: no more top and right "look like" same margin on the GoogleCast floating button above the heart stage card.

2024-08-16 11:19 UTC, pyby commented on Application/Sources/UI/Controllers/TabBarController.m
> +        _playerBottomToViewConstraint = [self.miniPlayerView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor];
Running on iPadOS less than 18.0, the mini player is now not visible, as displayed below the bottom tab bar.

The new condition should be only for iPadOS 18 and more.

2024-08-16 11:19 UTC, pyby commented on Application/Sources/UI/Controllers/TabBarController.m
> +        }
Are the two contraints compatible in the same time as they are link both to `self.miniPlayerView.bottomAnchor`?
Do we expect to set `active = NO` to one, and `active = YES` to the other one?

2024-11-18 18:33 UTC, defagos commented on Application/Sources/Bridges/SwiftMessagesBridge.swift
> +            }
Combining the `else` with the enclosed `if` is a bit more readable:

```suggestion
        }
        else if let presentationController {
            config.presentationContext = .viewController(presentationController)
```

2024-11-18 18:53 UTC, defagos commented on Application/Sources/UI/Controllers/TabBarController.m
> +        }
```suggestion
        BOOL isRegular = (self.traitCollection.horizontalSizeClass == UIUserInterfaceSizeClassRegular);
        self.playerBottomToViewConstraint.active = ! isRegular;
        self.playerBottomToSafeAreaConstraint.active = isRegular;
```

2024-11-26 07:14 UTC, defagos commented on Application/Sources/UI/Controllers/TabBarController.m
There is still sadly an issue with the player bar position on iPadOS 18 (compact layout):

![iPad compact](https://github.com/user-attachments/assets/f6da57cc-fcf4-4599-8117-70bca9b923ff)

2024-12-04 18:15 UTC, pyby approved these changes
Nice job done!

2024-12-04 18:15 UTC, pyby commented on Application/Sources/UI/Controllers/TabBarController.m
> +                        self.playerBottomToViewConstraint.constant = -self.tabBar.bounds.size.height;
```suggestion
                        self.playerBottomToViewConstraint.constant = -self.tabBar.bounds.size.height - self.miniPlayerOffset + self.view.safeAreaInsets.bottom;
```

To have same bottom space on iPad compact width, iPad OS 17 or iPad OS 18.

![Screenshot 2024-12-04 at 18 52 44](https://github.com/user-attachments/assets/8a5b4544-8f59-46d5-943f-bc3eb518681b)
![Screenshot 2024-12-04 at 18 52 49](https://github.com/user-attachments/assets/c9c46449-da6b-4d8f-9b8a-a5666ed324a2)

2024-12-04 19:45 UTC, merged